In [2]:
from one.api import ONE
import numpy as np

ONE.setup(base_url='https://openalyx.internationalbrainlab.org', silent=True)
one = ONE(password='international')

# Search for all experiments with channels.mlapdv dataset
eids = one.search(dataset='channels.mlapdv')

Connected to https://openalyx.internationalbrainlab.org as user "intbrainlab"


In [4]:
len(eids)

489

In [7]:
mlapdv_concat = []
probe00_eids = []
for eid in eids:
    try:
        mlapdv = one.load_dataset(eid, 'channels.mlapdv.npy', collection='alf/probe00/pykilosort')
        print(mlapdv.shape)
        mlapdv_mean = np.mean(mlapdv, axis=0) # compute the mean of the mlpadv values
        mlapdv_concat.append(mlapdv_mean)
        probe00_eids.append((eid, 'probe00'))
    except:
        pass

(384, 3)
(384, 3)
(384, 3)
(384, 3)


local md5 mismatch on dataset: cortexlab/Subjects/KS074/2021-11-22/001/alf/probe00/pykilosort/channels.mlapdv.npy
(S3) /home/maria/Downloads/ONE/openalyx.internationalbrainlab.org/cortexlab/Subjects/KS074/2021-11-22/001/alf/probe00/pykilosort/channels.mlapdv.npy: 100%|██████████| 4.74k/4.74k [00:00<00:00, 15.4kB/s]


(384, 3)
(384, 3)
(384, 3)
(384, 3)
(384, 3)
(384, 3)
(384, 3)
(384, 3)
(384, 3)
(384, 3)
(384, 3)
(384, 3)
(384, 3)
(384, 3)
(384, 3)
(384, 3)
(384, 3)
(384, 3)


In [6]:
mlapdv_concat

[array([-2322.82291667, -2417.08854167, -1982.21875   ]),
 array([ -968.91666667, -1526.13541667, -2544.36979167]),
 array([ -710.82291667,  1215.67708333, -2976.484375  ]),
 array([-1959.94270833, -2271.859375  , -2101.671875  ]),
 array([-2012.66666667, -2007.85416667, -1870.71354167]),
 array([-2116.18229167, -2290.046875  , -2106.1875    ]),
 array([-1821.78125   , -2609.59375   , -2644.38541667]),
 array([-2008.01041667, -1571.21875   , -2485.83854167]),
 array([-2296.66145833, -1752.85416667, -3154.765625  ]),
 array([-1725.88020833, -2446.234375  , -2055.19270833]),
 array([-2066.61979167, -2732.47916667, -2043.390625  ]),
 array([-1914.02604167, -2173.36458333, -2215.36458333]),
 array([-1639.9375    , -2275.        , -2488.60416667]),
 array([-1845.63020833, -2329.453125  , -2306.3125    ]),
 array([-2123.484375  , -3156.69791667, -2754.33854167]),
 array([-1949.69270833, -2113.3125    , -1933.53125   ]),
 array([-2061.515625, -2015.5     , -2340.859375]),
 array([-1926.270833